/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {
  "accordion": {
    name: "accordion",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "src/registry/default/ui/accordion.tsx",
      type: "registry:ui",
      target: ""
    },{
      path: "src/registry/default/slot-recipes/accordion.ts",
      type: "registry:slot-recipe",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/accordion.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "alert": {
    name: "alert",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "src/registry/default/ui/alert.tsx",
      type: "registry:ui",
      target: ""
    },{
      path: "src/registry/default/slot-recipes/alert.ts",
      type: "registry:slot-recipe",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/alert.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "alert-dialog": {
    name: "alert-dialog",
    description: "",
    type: "registry:ui",
    registryDependencies: ["button"],
    files: [{
      path: "src/registry/default/ui/alert-dialog.tsx",
      type: "registry:ui",
      target: ""
    },{
      path: "src/registry/default/slot-recipes/alert-dialog.ts",
      type: "registry:slot-recipe",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/alert-dialog.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "avatar": {
    name: "avatar",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "src/registry/default/ui/avatar.tsx",
      type: "registry:ui",
      target: ""
    },{
      path: "src/registry/default/slot-recipes/avatar.ts",
      type: "registry:slot-recipe",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/avatar.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "badge": {
    name: "badge",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "src/registry/default/ui/badge.tsx",
      type: "registry:ui",
      target: ""
    },{
      path: "src/registry/default/recipes/badge.ts",
      type: "registry:recipe",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/badge.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "breadcrumb": {
    name: "breadcrumb",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "src/registry/default/ui/breadcrumb.tsx",
      type: "registry:ui",
      target: ""
    },{
      path: "src/registry/default/slot-recipes/breadcrumb.ts",
      type: "registry:slot-recipe",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/breadcrumb.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "button": {
    name: "button",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "src/registry/default/ui/button.tsx",
      type: "registry:ui",
      target: ""
    },{
      path: "src/registry/default/recipes/button.ts",
      type: "registry:recipe",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/button.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "calendar": {
    name: "calendar",
    description: "",
    type: "registry:ui",
    registryDependencies: ["button"],
    files: [{
      path: "src/registry/default/ui/calendar.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/calendar.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "card": {
    name: "card",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "src/registry/default/ui/card.tsx",
      type: "registry:ui",
      target: ""
    },{
      path: "src/registry/default/slot-recipes/card.ts",
      type: "registry:slot-recipe",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/card.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "carousel": {
    name: "carousel",
    description: "",
    type: "registry:ui",
    registryDependencies: ["button"],
    files: [{
      path: "src/registry/default/ui/carousel.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/carousel.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "chart": {
    name: "chart",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "src/registry/default/ui/chart.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "checkbox": {
    name: "checkbox",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "src/registry/default/ui/checkbox.tsx",
      type: "registry:ui",
      target: ""
    },{
      path: "src/registry/default/slot-recipes/checkbox.ts",
      type: "registry:slot-recipe",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/checkbox.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "collapsible": {
    name: "collapsible",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "src/registry/default/ui/collapsible.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/collapsible.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "command": {
    name: "command",
    description: "",
    type: "registry:ui",
    registryDependencies: ["dialog"],
    files: [{
      path: "src/registry/default/ui/command.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/command.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "context-menu": {
    name: "context-menu",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "src/registry/default/ui/context-menu.tsx",
      type: "registry:ui",
      target: ""
    },{
      path: "src/registry/default/slot-recipes/context-menu.ts",
      type: "registry:slot-recipe",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/context-menu.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "dialog": {
    name: "dialog",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "src/registry/default/ui/dialog.tsx",
      type: "registry:ui",
      target: ""
    },{
      path: "src/registry/default/slot-recipes/dialog.ts",
      type: "registry:slot-recipe",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/dialog.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "drawer": {
    name: "drawer",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "src/registry/default/ui/drawer.tsx",
      type: "registry:ui",
      target: ""
    },{
      path: "src/registry/default/slot-recipes/drawer.ts",
      type: "registry:slot-recipe",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/drawer.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "dropdown-menu": {
    name: "dropdown-menu",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "src/registry/default/ui/dropdown-menu.tsx",
      type: "registry:ui",
      target: ""
    },{
      path: "src/registry/default/slot-recipes/dropdown-menu.ts",
      type: "registry:slot-recipe",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/dropdown-menu.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "field": {
    name: "field",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "src/registry/default/ui/field.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/field.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "hover-card": {
    name: "hover-card",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "src/registry/default/ui/hover-card.tsx",
      type: "registry:ui",
      target: ""
    },{
      path: "src/registry/default/slot-recipes/hover-card.ts",
      type: "registry:slot-recipe",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/hover-card.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "input": {
    name: "input",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "src/registry/default/ui/input.tsx",
      type: "registry:ui",
      target: ""
    },{
      path: "src/registry/default/recipes/input.ts",
      type: "registry:recipe",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/input.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "kbd": {
    name: "kbd",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "src/registry/default/ui/kbd.tsx",
      type: "registry:ui",
      target: ""
    },{
      path: "src/registry/default/recipes/kbd.ts",
      type: "registry:recipe",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/kbd.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "label": {
    name: "label",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "src/registry/default/ui/label.tsx",
      type: "registry:ui",
      target: ""
    },{
      path: "src/registry/default/recipes/label.ts",
      type: "registry:recipe",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/label.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "menubar": {
    name: "menubar",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "src/registry/default/ui/menubar.tsx",
      type: "registry:ui",
      target: ""
    },{
      path: "src/registry/default/slot-recipes/menubar.ts",
      type: "registry:slot-recipe",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/menubar.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "navigation-menu": {
    name: "navigation-menu",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "src/registry/default/ui/navigation-menu.tsx",
      type: "registry:ui",
      target: ""
    },{
      path: "src/registry/default/slot-recipes/navigation-menu.ts",
      type: "registry:slot-recipe",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/navigation-menu.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "pagination": {
    name: "pagination",
    description: "",
    type: "registry:ui",
    registryDependencies: ["button"],
    files: [{
      path: "src/registry/default/ui/pagination.tsx",
      type: "registry:ui",
      target: ""
    },{
      path: "src/registry/default/slot-recipes/pagination.ts",
      type: "registry:slot-recipe",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/pagination.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "phone-input": {
    name: "phone-input",
    description: "",
    type: "registry:ui",
    registryDependencies: ["button","input","popover","scroll-area","command"],
    files: [{
      path: "src/registry/default/ui/phone-input.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/phone-input.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "popover": {
    name: "popover",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "src/registry/default/ui/popover.tsx",
      type: "registry:ui",
      target: ""
    },{
      path: "src/registry/default/slot-recipes/popover.ts",
      type: "registry:slot-recipe",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/popover.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "progress": {
    name: "progress",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "src/registry/default/ui/progress.tsx",
      type: "registry:ui",
      target: ""
    },{
      path: "src/registry/default/slot-recipes/progress.ts",
      type: "registry:slot-recipe",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/progress.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "radio-group": {
    name: "radio-group",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "src/registry/default/ui/radio-group.tsx",
      type: "registry:ui",
      target: ""
    },{
      path: "src/registry/default/slot-recipes/radio-group.ts",
      type: "registry:slot-recipe",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/radio-group.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "resizable": {
    name: "resizable",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "src/registry/default/ui/resizable.tsx",
      type: "registry:ui",
      target: ""
    },{
      path: "src/registry/default/slot-recipes/resizable.ts",
      type: "registry:slot-recipe",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/resizable.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "scroll-area": {
    name: "scroll-area",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "src/registry/default/ui/scroll-area.tsx",
      type: "registry:ui",
      target: ""
    },{
      path: "src/registry/default/slot-recipes/scroll-area.ts",
      type: "registry:slot-recipe",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/scroll-area.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "select": {
    name: "select",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "src/registry/default/ui/select.tsx",
      type: "registry:ui",
      target: ""
    },{
      path: "src/registry/default/slot-recipes/select.ts",
      type: "registry:slot-recipe",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/select.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "separator": {
    name: "separator",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "src/registry/default/ui/separator.tsx",
      type: "registry:ui",
      target: ""
    },{
      path: "src/registry/default/recipes/separator.ts",
      type: "registry:recipe",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/separator.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "sheet": {
    name: "sheet",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "src/registry/default/ui/sheet.tsx",
      type: "registry:ui",
      target: ""
    },{
      path: "src/registry/default/slot-recipes/sheet.ts",
      type: "registry:slot-recipe",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/sheet.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "sidebar": {
    name: "sidebar",
    description: "",
    type: "registry:ui",
    registryDependencies: ["button","separator","sheet","tooltip","input","use-media-query","skeleton"],
    files: [{
      path: "src/registry/default/ui/sidebar.tsx",
      type: "registry:ui",
      target: ""
    },{
      path: "src/registry/default/hooks/use-media-query.ts",
      type: "registry:hook",
      target: ""
    },{
      path: "src/registry/default/slot-recipes/sidebar.ts",
      type: "registry:slot-recipe",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/sidebar.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "skeleton": {
    name: "skeleton",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "src/registry/default/ui/skeleton.tsx",
      type: "registry:ui",
      target: ""
    },{
      path: "src/registry/default/recipes/skeleton.ts",
      type: "registry:recipe",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/skeleton.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "slider": {
    name: "slider",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "src/registry/default/ui/slider.tsx",
      type: "registry:ui",
      target: ""
    },{
      path: "src/registry/default/slot-recipes/slider.ts",
      type: "registry:slot-recipe",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/slider.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "sonner": {
    name: "sonner",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "src/registry/default/ui/sonner.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/sonner.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "switch": {
    name: "switch",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "src/registry/default/ui/switch.tsx",
      type: "registry:ui",
      target: ""
    },{
      path: "src/registry/default/slot-recipes/switch.ts",
      type: "registry:slot-recipe",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/switch.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "table": {
    name: "table",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "src/registry/default/ui/table.tsx",
      type: "registry:ui",
      target: ""
    },{
      path: "src/registry/default/slot-recipes/table.ts",
      type: "registry:slot-recipe",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/table.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "tabs": {
    name: "tabs",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "src/registry/default/ui/tabs.tsx",
      type: "registry:ui",
      target: ""
    },{
      path: "src/registry/default/slot-recipes/tabs.ts",
      type: "registry:slot-recipe",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/tabs.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "textarea": {
    name: "textarea",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "src/registry/default/ui/textarea.tsx",
      type: "registry:ui",
      target: ""
    },{
      path: "src/registry/default/recipes/textarea.ts",
      type: "registry:recipe",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/textarea.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "timeline": {
    name: "timeline",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "src/registry/default/ui/timeline.tsx",
      type: "registry:ui",
      target: ""
    },{
      path: "src/registry/default/slot-recipes/timeline.ts",
      type: "registry:slot-recipe",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/timeline.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "toast": {
    name: "toast",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "src/registry/default/ui/toast.tsx",
      type: "registry:ui",
      target: ""
    },{
      path: "src/registry/default/hooks/use-toast.ts",
      type: "registry:hook",
      target: ""
    },{
      path: "src/registry/default/ui/toaster.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/toast.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "toggle": {
    name: "toggle",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "src/registry/default/ui/toggle.tsx",
      type: "registry:ui",
      target: ""
    },{
      path: "src/registry/default/recipes/toggle.ts",
      type: "registry:recipe",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/toggle.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "toggle-group": {
    name: "toggle-group",
    description: "",
    type: "registry:ui",
    registryDependencies: ["toggle"],
    files: [{
      path: "src/registry/default/ui/toggle-group.tsx",
      type: "registry:ui",
      target: ""
    },{
      path: "src/registry/default/slot-recipes/toggle-group.ts",
      type: "registry:slot-recipe",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/toggle-group.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "tooltip": {
    name: "tooltip",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "src/registry/default/ui/tooltip.tsx",
      type: "registry:ui",
      target: ""
    },{
      path: "src/registry/default/slot-recipes/tooltip.ts",
      type: "registry:slot-recipe",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/tooltip.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "use-media-query": {
    name: "use-media-query",
    description: "",
    type: "registry:hook",
    registryDependencies: undefined,
    files: [{
      path: "src/registry/default/hooks/use-media-query.ts",
      type: "registry:hook",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/hooks/use-media-query.ts")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "use-toast": {
    name: "use-toast",
    description: "",
    type: "registry:hook",
    registryDependencies: undefined,
    files: [{
      path: "src/registry/default/hooks/use-toast.ts",
      type: "registry:hook",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/hooks/use-toast.ts")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "create-style-context": {
    name: "create-style-context",
    description: "",
    type: "registry:lib",
    registryDependencies: undefined,
    files: [{
      path: "src/registry/default/lib/create-style-context.tsx",
      type: "registry:lib",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/lib/create-style-context.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  }